services:
  - type: web
    name: konsumsi_listrik-25-30
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
